import {selection,districtRows,districtHref,stateMultilingual,count,percent,csvRows} from '../lib/language-atlas.mjs';
const data=JSON.parse(document.getElementById('language-atlas-data')!.textContent!);
const el=(id:string)=>document.getElementById('atlas-'+id)!;
const control=(id:string)=>el(id) as HTMLInputElement|HTMLSelectElement;
function restore(){const p=new URLSearchParams(location.search),s=selection(data,p.get('language')||undefined,p.get('residence')||undefined);control('language').value=s.code;control('residence').value=s.residence;control('sort').value=['count','share','name'].includes(p.get('sort')||'')?p.get('sort')!:'count';control('query').value=p.get('district')||'';}
function refresh(updateUrl=false){
 const s=selection(data,control('language').value,control('residence').value),rows=districtRows(data,s.code,s.residence,control('sort').value,control('query').value);
 const area=s.residence==='total'?'all areas':s.residence+' areas',group=s.label.level==='language_group';
 el('label').textContent=s.label.label+' · '+(group?'Census language group':'individual mother-tongue entry');el('count').textContent=count(s.persons);el('share').textContent=s.share;el('breakdown').textContent=count(s.males)+' male · '+count(s.females)+' female';el('share-label').textContent='Share of Odisha’s population · '+area;el('denominator').textContent='Out of '+count(s.population)+' people, Census 2011';
 el('selection-note').textContent=group?'Census language group '+s.label.label+'. Its total contains the mother-tongue entries listed beneath it; do not add parent and child totals.':'Individual entry '+s.label.label+', classified under '+data.labels[s.label.parent].label+' in Census 2011. This source classification does not decide community identity or preferred naming.';
 const p=Object.values(data.profiles).find((p:any)=>p.code===s.code) as any;if(p?.note)el('selection-note').textContent+=' '+p.note;
 el('results').textContent=rows.length+' of 30 districts · '+s.label.label+' · '+area;el('caption').textContent=s.label.label+' · district population, Census 2011 · '+area;
 const body=el('rows');body.replaceChildren();for(const r of rows){const tr=document.createElement('tr'),th=document.createElement('th');th.scope='row';const link=document.createElement('a');link.href=districtHref(data.areas[r.code]);link.textContent=r.name;th.append(link);tr.append(th);for(const text of [r.persons===null?'Not separately listed':count(r.persons),r.persons===null?'—':percent(r.persons,r.population),r.persons===null?'—':percent(r.persons,s.persons)]){const td=document.createElement('td');td.textContent=text;tr.append(td)}const track=document.createElement('span'),bar=document.createElement('span');track.className='atlas-bar';track.setAttribute('aria-hidden','true');bar.style.width=Math.max(0,r.share||0)+'%';track.append(bar);tr.children[2].append(track);body.append(tr)}el('empty').hidden=rows.length>0;
 const multi=stateMultilingual(data,s.code);el('multi').textContent=multi?`${count(multi.at_least_two_languages[0])} people in the ${s.label.label} group reported at least one additional language (${percent(multi.at_least_two_languages[0],multi.population[0])}). Of these, ${count(multi.three_languages[0])} reported two additional languages. Statewide, all areas, Census 2011.`:'The C-17 table reports multilingualism for parent language groups. Select '+data.labels[s.label.parent].label+' under “Census language groups” to explore that wider group; its counts cannot be assigned to this individual entry.';
 if(updateUrl){const u=new URL(location.href);u.searchParams.set('language',s.code);u.searchParams.set('residence',s.residence);u.searchParams.set('sort',control('sort').value);const q=control('query').value.trim();q?u.searchParams.set('district',q):u.searchParams.delete('district');history.replaceState(null,'',u)}
}
restore();refresh();for(const id of ['language','residence','sort'])control(id).addEventListener('change',()=>refresh(true));control('query').addEventListener('input',()=>refresh(true));window.addEventListener('popstate',()=>{restore();refresh()});
el('download').addEventListener('click',()=>{const s=selection(data,control('language').value,control('residence').value),rows=districtRows(data,s.code,s.residence,control('sort').value,control('query').value),url=URL.createObjectURL(new Blob(['\ufeff'+csvRows(rows,s)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`utkal-census-2011-${s.code}-${s.residence}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
