"""Validate candidate identities and submission safeguards, not GI eligibility."""
import json,sys
from kb_io import ROOT
x=json.loads((ROOT/'references/data/gi-opportunities.json').read_text());errors=[]
def ck(v,m):
 if not v:errors.append(m)
cs=x['candidates'];ids=[c['id'] for c in cs];apps={int(a['Application Number']):a for a in x['application_checks']}
ck(len(ids)==len(set(ids)),'Duplicate candidate ID')
for c in cs:
 ck(all((ROOT/p).is_file() for p in c['reuse_paths']),'Missing reuse page '+c['id'])
 ck(not c['ready_to_file'] and not c['filed_by_utkal'],'Premature filing claim '+c['id'])
 ck(not c['producer_mandate_received'] and not c['eligible_applicant_confirmed'],'Invented applicant '+c['id'])
 ck(c['sales'] is None and c['export_value'] is None,'Unsupported economics '+c['id'])
ck(all(v is False for v in x['controls'].values()),'Evidence safeguard changed')
ck(all(apps[i]['Status']=='Registered' for i in x['indian_comparator_ids']),'Unregistered comparator promoted')
ck(apps[682]['Status']=='withdrawn' and apps[594]['Status']=='Registered','Gamocha application identities conflated')
ck(apps[2117]['Status']=='New Application','Manikapatna filing status drift')
ck(apps[805]['Status']==apps[797]['Status']=='Examination','Palm-leaf applications status drift')
ck(any(c['id']=='GI-C002' and c['research_stage']=='identity_unresolved' for c in cs),'User name ambiguity lost')
ck(bool(x['registry_screen']['absence_meaning']),'Bounded search limitation lost')
specs=x.get('specification_comparisons',[])
ck({v['application_number'] for v in specs}=={584,655},'Original specification identities incomplete')
for v in specs:
 ck(v['evidence_class']=='advertised_applicant_specification','Source class lost')
 ck((ROOT/('sources/'+v['source_id']+'.md')).is_file(),'Missing specification source')
 ck(not v['recipe_ready'] and not v['place_link_independently_verified'] and not v['current_enforcement_verified'],'Unverified specification promoted')
holds={v['id']:v for v in x.get('specification_holds',[])}
ck(holds.get('GI-HOLD-SILAO-FAT',{}).get('status')=='conflicted','Ingredient conflict lost')
ck(holds.get('GI-HOLD-GOA-UTENSIL',{}).get('status')=='quarantined','Utensil wording hold lost')
ck(holds.get('GI-HOLD-GOA-ECONOMICS',{}).get('status')=='excluded_from_quantitative_comparison','Economic scope hold lost')
tx=x.get('textile_comparison',{})
ck(tx.get('application_number')==594,'Textile application identity lost')
ck({v['publication_date'] for v in tx.get('editions',[])}=={'2019-10-24','2022-08-12'},'Textile edition history lost')
ck(not tx.get('puri_specification_established',True) and not tx.get('current_enforcement_verified',True),'Comparator promoted to Puri specification or current enforcement')
for v in tx.get('editions',[]):ck((ROOT/('sources/'+v['source_id']+'.md')).is_file(),'Missing textile source')
lead=next(c for c in cs if c['id']=='GI-C004')['identity_leads'][0]
ck(not lead['confirmed_match_to_user_candidate'] and lead['technical_specification'] is None,'Reported local lead promoted')
ck(holds.get('GI-HOLD-GAMOSA-ANAKATA',{}).get('status')=='conflicted','Textile dimension conflict lost')
tf=x.get('temple_food_comparison',{})
ck(tf.get('application_number')==121 and tf.get('public_availability_date')=='2008-11-24','Temple comparator identity/date lost')
ck(not tf.get('puri_eligibility_established',True) and not tf.get('recipe_ready',True),'Temple comparator promoted to eligibility or recipe')
ck((ROOT/('sources/'+tf.get('source_id','')+'.md')).is_file(),'Missing temple specification source')
ck(holds.get('GI-HOLD-LADDU-WEIGHT',{}).get('status')=='unreconciled_vintages','Weight vintages silently reconciled')
ck(holds.get('GI-HOLD-LADDU-TEMPERATURE',{}).get('status')=='quarantined','Temperature hold lost')
ck(holds.get('GI-HOLD-LADDU-AU',{}).get('observed_status','missing') is None,'Blank authorized-user status promoted')
nc=next(c for c in cs if c['id']=='GI-C001')
chron=nc.get('name_use_chronology',[])
ck(len(chron)==4 and all(v.get('origin_date','missing') is None for v in chron),'Name-use dates promoted to origin dates')
ck(len({v['family'] for v in chron if v['source_id'].startswith('gi-puri-msme')})==1,'Repeated MSME editions treated as independent')
ck(next((v for v in chron if v['source_id']=='gi-puri-msme2016'),{}).get('edition')=='2016–17','Cover edition lost')
ck(not nc.get('attribution_limits',{}).get('operating_cluster_verified',True),'Prospect promoted to operating cluster')
ck(all(v['publication_date'] is None for v in chron if v['date_basis']=='file_metadata_only'),'File metadata promoted to publication date')
kc=next(c for c in cs if c['id']=='GI-C008')
kg=kc.get('goods_scope',{})
ck(kg.get('geography')=='Bhubaneswar Old Town, Khordha district' and not kg.get('puri_origin_established',True),'Korakhai geography conflated')
ck(not kg.get('tested_recipe',True) and kg.get('measured_process','missing') is None,'Reported preparation promoted to measured recipe')
kr={v['source_id']:v for v in kc.get('documentary_records',[])}
ck(not kr.get('gi-korakhai-college2025',{}).get('official_odop_designation_established',True),'College theme promoted to official ODOP')
ck(not kr.get('gi-korakhai-bda2022',{}).get('operation_verified',True),'Proposed trail promoted to operation')
mc=next(c for c in cs if c['id']=='GI-C009')
mr=mc.get('dossier_review',{})
ck(mr.get('certificate_kind')=='ICAR animal breed registration' and not mr.get('gi_registration_established',True),'Breed certificate promoted to GI award')
ck(mr.get('notice_requirement_count')==25 and mr.get('deadline','missing') is None and not mr.get('abandonment_verified',True),'Notice date promoted to deadline or abandonment')
ck(not mr.get('inspection_body_operating_verified',True) and not mr.get('shelf_life_advice_validated',True),'Submitted proposal promoted to operation or safety advice')
ck(holds.get('GI-HOLD-MANIKAPATNA-PH',{}).get('status')=='unreconciled_scopes','Manikapatna pH scope hold lost')
ss={v['id']:v for v in mc.get('science_studies',[])}
cs13=ss.get('CURD-STUDY-2013',{})
ck(cs13.get('milk_samples')==10 and cs13.get('curd_samples')==10 and cs13.get('followup_days')==14 and cs13.get('reported_stability_days')==7,'Sample/observation/stability scopes conflated')
ck(not cs13.get('consumer_shelf_life_validated',True) and not cs13.get('clinical_trial',True),'Laboratory observations promoted to consumer or clinical advice')
ck(cs13.get('antifungal_stronger',0)+cs13.get('antifungal_weaker',0)+cs13.get('positive_not_reported',0)==cs13.get('lactobacillus_tested',-1),'Antifungal screening denominator inconsistent')
ck(not ss.get('CURD-STUDY-2024',{}).get('independent_field_replication',True),'Culture follow-up promoted to independent field replication')
ck(holds.get('GI-HOLD-CURD-STRAINS',{}).get('status')=='conflicted','Culture identity conflict lost')
pc=next(c for c in cs if c['id']=='GI-C010')['dossier_review']
ck({v['application_number'] for v in pc['applications']}=={797,805},'Palm application identities lost')
ck(set(pc['shared_submitted_districts_2021'])=={'Puri','Khordha'},'Historical overlap drift')
ck(not pc['boundary_accepted'] and not pc['identity_determination_verified'] and not pc['gi_registration_established'],'Applicant scope promoted to accepted GI')
ck(pc['deadline'] is None and not pc['abandonment_verified'],'Communication-based deadline invented')
ck(pc['reply_review']['reviewed_pdf_pages']==list(range(1,91)) and not pc['reply_review']['complete_amended_file_review'],'Partial reply promoted to complete review')
ck(not pc['reply_review']['class16_request_vs_class27_response_reconciled'],'Unresolved class scope silently settled')
ck(pc['reply_review']['unreviewed_parts']==[] and pc['reply_review']['partially_reviewed_parts']==[2,3] and pc['reply_review']['part1_text_review_complete'],'Reply part coverage drift')
ck(not pc['proposed_watchdog']['operating_verified'] and not pc['proposed_watchdog']['appointments_verified'],'Proposed watchdog promoted to operation')
ck(pc['representation_followup']['current_active_producers'] is None and not pc['representation_followup']['authorized_user_registration_verified'],'Applicant claims promoted to current producer census or authorized-user registration')
ck(holds['GI-HOLD-PALM-DIMENSIONS']['unit'] is None,'Missing product units inferred')
ck(not holds['GI-HOLD-PALM-ECONOMICS']['palm_leaf_specific'] and holds['GI-HOLD-PALM-ECONOMICS']['growth_rate'] is None,'Broader handicraft sales promoted to craft growth')
ck(holds['GI-HOLD-PALM-PLANT']['scientific_name'] is None and not holds['GI-HOLD-PALM-PLANT']['exclusive_distribution_verified'],'Vernacular leaf label promoted to botanical identity or exclusivity')
ck(pc['representation_followup']['producer_roster_inspected'] and pc['representation_followup']['roster']['unique_people'] is None,'Historical roster missing or promoted to unique people')
ck(not pc['representation_followup']['roster']['consent_verified'] and not pc['representation_followup']['roster']['personal_rows_exported'],'Roster consent or personal-data export drift')
ck(pc['representation_followup']['applicant_amendment_accepted'] is None and holds['GI-HOLD-PALM-APPLICANTS']['accepted_amendment'] is None,'Submitted joint applicants promoted to accepted amendment')
ck(not pc['representation_followup']['corporation_bylaw_amendment']['is_kvk_certificate'] and not pc['representation_followup']['corporation_bylaw_amendment']['is_gi_boundary'],'Corporation certificate scope drift')
gc=next(c for c in x['candidates'] if c['id']=='GI-C006')
kc=next(c for c in x['candidates'] if c['id']=='GI-C007')
ck(gc['goods_identity']['names_equivalent'] is None and kc['goods_identity']['names_equivalent'] is None,'Related sweet names merged without evidence')
ck(not kc['goods_identity']['ingredient_scope_reconciled'] and holds['GI-HOLD-KANTI-IDENTITY']['same_recipe'] is None,'Source-specific Kanti ingredients merged into recipe')
for cid in ['GI-C011','GI-C012']:
 ps=next(c for c in cs if c['id']==cid)['place_scope']
 ck(not ps['exclusive_puri_origin_verified'] and ps['distinct_puri_specification'] is None and ps['temple_recipe_matched'] is None,'Association promoted to exclusive origin or agreed temple recipe '+cid)
 ck(not ps['tested_recipe'] and not ps['consumer_shelf_life_validated'] and ps['current_market_data'] is None,'Recipe compilation promoted to process validation or market data '+cid)
ck(holds['GI-HOLD-PITHA-PLACE-SCOPE']['accepted_specification'] is None,'Unresolved local product scope silently accepted')
ra=x['readiness_assessment'];rr=ra['rows']
ck(len(rr)==len(cs) and {r['candidate_id'] for r in rr}==set(ids),'Readiness matrix omits or duplicates candidates')
ck(sum(ra['route_counts'].values())==len(rr),'Readiness route counts mismatch')
for route,n in ra['route_counts'].items():ck(n==sum(r['route']==route for r in rr),'Readiness route count drift '+route)
for r in rr:
 ck((ROOT/r['dossier_path']).is_file() and bool(r['evidence_to_close_next_step']),'Readiness evidence link or closure condition missing')
 ck(not r['ready_to_file'] and not r['outreach_sent'] and r['human_owner'] is None,'Readiness synthesis invented action or owner')
ck(not ra['fresh_publisher_check'] and ra['ready_to_file_count']==sum(r['ready_to_file'] for r in rr),'Synthesis promoted to publisher check or filing readiness')
print(json.dumps({'result':'FAIL' if errors else 'PASS','candidate_leads':len(cs),'comparators':len(x['indian_comparator_ids']),'original_specifications':len(specs)+2,'textile_editions':len(tx['editions']),'specification_holds':len(holds),'ready_to_file':sum(c['ready_to_file'] for c in cs),'errors':errors,'scope':'Identity and stage safeguards, not eligibility, producer mandate or legal clearance.'},indent=2));sys.exit(bool(errors))
