const version='0.1.0-rc.4',key='utkal-design-system:review:'+version;
const status=document.querySelector('#review-status');
const groups=[...document.querySelectorAll('[data-review]')];
const valid=new Set(['unreviewed','prefer','revise']);
let storageWorks=true;
try{const stored=JSON.parse(localStorage.getItem(key)||'null');if(stored?.version===version&&stored.groups&&typeof stored.groups==='object')for(const group of groups){const row=stored.groups[group.dataset.review];if(row&&valid.has(row.choice)){group.querySelector('[data-choice]').value=row.choice;group.querySelector('[data-note]').value=typeof row.note==='string'?row.note.slice(0,2000):'';}}}catch{storageWorks=false;status.textContent='Saved review could not be read. Export your notes before leaving; existing data will not be overwritten.';}
function snapshot(){return {version,status:'review_preferences_not_approval',recorded_at:new Date().toISOString(),groups:Object.fromEntries(groups.map(g=>[g.dataset.review,{choice:g.querySelector('[data-choice]').value,note:g.querySelector('[data-note]').value}]))};}
function count(){return groups.filter(g=>g.querySelector('[data-choice]').value!=='unreviewed').length;}
function save(){try{if(!storageWorks)throw Error();localStorage.setItem(key,JSON.stringify(snapshot()));status.textContent=`${count()} of ${groups.length} groups reviewed. Saved in this browser; export for handoff.`;}catch{storageWorks=false;status.textContent='Review is available on this page only. Export your notes before leaving.';}}
if(storageWorks&&count())status.textContent=`${count()} of ${groups.length} groups restored from this browser.`;
for(const group of groups)group.addEventListener('input',save);
document.querySelector('#export-review').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='utkal-design-system-review-'+version+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Review notes downloaded. No project change or publication was applied.';});
document.querySelector('#text-size').addEventListener('click',e=>{const on=document.documentElement.classList.toggle('enlarged');e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=on?'Return to normal text':'Review at 200% text';});
for(const mode of ['proposed','current'])document.querySelector('#type-'+mode).addEventListener('click',()=>{document.querySelector('#type-specimen').classList.toggle('current',mode==='current');document.querySelector('#type-caption').textContent=mode==='current'?'Comparison · current Georgia':'Display · Cormorant Garamond 500';for(const m of ['proposed','current'])document.querySelector('#type-'+m).setAttribute('aria-pressed',String(m===mode));});
document.querySelector('#demo-save').addEventListener('click',e=>{const b=e.currentTarget,on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(on));b.querySelector('span').textContent=on?'Saved to this sample':'Save this idea';document.querySelector('#save-status').textContent=on?'Saved in this sample only. No journey was changed.':'Removed from this sample. No journey was changed.';});
function filter(){const q=document.querySelector('#demo-query').value.toLowerCase().trim().split(/\s+/).filter(Boolean),category=document.querySelector('#demo-subject').value;let n=0;for(const card of document.querySelectorAll('[data-discovery]')){const show=(category==='All'||category===card.dataset.category)&&q.every(word=>card.dataset.search.includes(word));card.hidden=!show;if(show)n++;}document.querySelector('#discovery-status').textContent=`${n} ${n===1?'discovery':'discoveries'}`;document.querySelector('#no-discoveries').hidden=n>0;}
document.querySelector('#demo-search').addEventListener('submit',e=>{e.preventDefault();filter();});document.querySelector('#demo-subject').addEventListener('change',filter);document.querySelector('#demo-clear').addEventListener('click',()=>{document.querySelector('#demo-search').reset();filter();document.querySelector('#demo-query').focus();});
document.querySelector('#demo-contribution').addEventListener('submit',e=>{e.preventDefault();const text=document.querySelector('#demo-story'),evidence=document.querySelector('#demo-evidence'),message=document.querySelector('#demo-form-status');for(const el of [text,evidence]){el.removeAttribute('aria-invalid');el.setAttribute('aria-describedby',el.id+'-help');}const bad=text.value.trim().length<10?text:evidence.value.trim().length<5?evidence:null;if(bad){bad.setAttribute('aria-invalid','true');bad.setAttribute('aria-describedby',bad.id+'-help demo-form-status');message.className='utk-error';message.textContent=bad===text?'Describe your contribution in at least ten characters.':'Add a source or firsthand context in at least five characters.';bad.focus();}else{message.className='utk-message utk-message--success';message.textContent='The sample is ready for preview. Nothing has been sent or saved.';}});
function pilot(){const id=document.querySelector('#pilot-page').value,view='integrated',src=`pilots/${id}/?view=${view}`;document.querySelector('#pilot').src=src;document.querySelector('#pilot').title=document.querySelector('#pilot-page').selectedOptions[0].textContent+' · '+view;document.querySelector('#open-pilot').href=src;document.querySelector('.pilot-frame').style.width=document.querySelector('#pilot-width').value==='390'?'390px':'100%';}
for(const id of ['pilot-page','pilot-width'])document.querySelector('#'+id).addEventListener('change',pilot);
